### ISSUE TITLE
Api pack dependency - 1.2 not working

### ISSUE THREAD

**Issue by treatys** [Locastic/ApiPlatformTranslationBundle#11]
Tried to install the package via composer, got an error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for locastic/api-platform-translation-bundle dev-master -> satisfiable by locastic/api-platform-translation-bundle[dev-master].
    - locastic/api-platform-translation-bundle dev-master requires api-platform/api-pack ^1.1 -> satisfiable by api-platform/api-pack[1.1.0, v1.2.0] but these conflict with you
r requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```
I guess it's only matter of incorrectly defined dependency on api-pack instead of api-core. Refering to #4. Can you please change composer.json to make it work? 

I have to use Gedmo which philosophy and approach I cannot agree instead of Locastic. Thanks.

**Comment by paullla** [comment]
Hi @treatys, dependency is changed to core in https://github.com/Locastic/ApiPlatformTranslationBundle/pull/17. Let me know if you have any more issues.
