### ISSUE TITLE
No locale has been set and current locale is undefined.

### ISSUE THREAD

**Issue by winzza** [Locastic/ApiPlatformTranslationBundle#15]
I did everything according to this instruction
https://github.com/Locastic/ApiPlatformTranslationBundle

And i get error after post method:
`
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "No locale has been set and current locale is undefined.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/site/vendor/locastic/api-platform-translation-bundle/src/Model/TranslatableTrait.php",
      "line": 64,
      "args": []
    },
    ....
}
`
(I use symfony5)

**Comment by paullla** [comment]
Hi @winzza, sorry for the slower response, I’ve been really busy with projects and conferences lately. Can you take a look at https://github.com/Locastic/ApiPlatformTranslationBundle/issues/18. Maybe you are missing parent constructor call too. If that's not the case, can you post your code for classes using Translation and Translatable classes so we could detect the problem?

**Comment by paullla** [comment]
Issue is fixed with https://github.com/Locastic/ApiPlatformTranslationBundle/pull/19
