### ISSUE TITLE
inconsistency of returning types

### ISSUE THREAD

**Issue by yalagin** [Locastic/ApiPlatformTranslationBundle#42]
there is an inconsistency of returning types when translation is empty it's returning array instead of object 

no translations 
```js
{
"id":1,
 "translations": []
}
```
there are translations
```js
{
"id":1,
 "translations": { 
        "en":{
            "title":"test",
            "content":"test",
            "locale":"en"
        },
        "de":{
            "title":"test de",
            "content":"test de",
            "locale":"de"
        }
    }
}
```

maybe it's should return {}  or null if there are no translations

**Comment by yalagin** [comment]
well, I took a look at why it's serializing an array. it's because of https://github.com/symfony/symfony/issues/37061 and https://github.com/symfony/symfony/pull/37049
why translation should be an object to submit and get, why the user is not permitted to submit an array of translations?

**Comment by paullla** [comment]
@yalagin thank you for reporting. I'm closing it since it's Symfony issue
