### ISSUE TITLE
support api-platform/core^3.0@rc

### ISSUE THREAD

**Issue by yalagin** [Locastic/ApiPlatformTranslationBundle#58]
locastic/api-platform-translation-bundle[v1.3, ..., v1.3.4] require api-platform/core ^2.1 -> found api-platform/core[v2.1.0, ..., v2.7.0-rc.2] but it conflicts with your root composer.json require (^3.0@rc).

**Comment by paullla** [comment]
ApiPlatform 3.0 is now supported: https://github.com/Locastic/ApiPlatformTranslationBundle/pull/59
