### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by julien-jourde** [Locastic/ApiPlatformTranslationBundle#66]
Hello,
Do you have a release date for a new version? Especially for the last fix https://github.com/Locastic/ApiPlatformTranslationBundle/commit/09437e2ba9e19bcba6f9ef5f004912a3725309bb

**Comment by paullla** [comment]
Hey @julien-jourde , I just made a new release which includes the last fix: https://github.com/Locastic/ApiPlatformTranslationBundle/tree/v1.3.7

**Comment by julien-jourde** [comment]
Great job !
Thank you :+1:
