### ISSUE TITLE
Doctrine/orm 3 support

### ISSUE THREAD

**Issue by russelomua** [Locastic/ApiPlatformTranslationBundle#69]
Dear maintainers, 

could we kindly request the inclusion of support for `doctrine/orm 3`? @konradkozaczenko has already submitted GH-68. `Doctrine/orm 3` requires `PHP 8.1+`, so this release may require updating the `package.json` to reflect the change. Given the substantial implications, I think the release with this updates must be major version.

Best regards!

**Comment by paullla** [comment]
hey @russelomua , the PR is not yet fully ready to be merged, but as soon as it is we will tag a new version.

**Comment by paullla** [comment]
the new 1.4 version is now available with ORM 3 support :)
